package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1



/**
 * AgmaeProvinciaId generated by hbm2java
 */
public class AgmaeProvinciaId  implements java.io.Serializable {


     private int codDepartamento;
     private int codProvincia;

    public AgmaeProvinciaId() {
    }

    public AgmaeProvinciaId(int codDepartamento, int codProvincia) {
       this.codDepartamento = codDepartamento;
       this.codProvincia = codProvincia;
    }
   
    public int getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(int codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public int getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(int codProvincia) {
        this.codProvincia = codProvincia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgmaeProvinciaId) ) return false;
		 AgmaeProvinciaId castOther = ( AgmaeProvinciaId ) other; 
         
		 return (this.getCodDepartamento()==castOther.getCodDepartamento())
 && (this.getCodProvincia()==castOther.getCodProvincia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodDepartamento();
         result = 37 * result + this.getCodProvincia();
         return result;
   }   


}


