package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1



/**
 * AgmaeDistritoId generated by hbm2java
 */
public class AgmaeDistritoId  implements java.io.Serializable {


     private int codDepartamento;
     private int codProvincia;
     private int codDistrito;

    public AgmaeDistritoId() {
    }

    public AgmaeDistritoId(int codDepartamento, int codProvincia, int codDistrito) {
       this.codDepartamento = codDepartamento;
       this.codProvincia = codProvincia;
       this.codDistrito = codDistrito;
    }
   
    public int getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(int codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public int getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(int codProvincia) {
        this.codProvincia = codProvincia;
    }
    public int getCodDistrito() {
        return this.codDistrito;
    }
    
    public void setCodDistrito(int codDistrito) {
        this.codDistrito = codDistrito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgmaeDistritoId) ) return false;
		 AgmaeDistritoId castOther = ( AgmaeDistritoId ) other; 
         
		 return (this.getCodDepartamento()==castOther.getCodDepartamento())
 && (this.getCodProvincia()==castOther.getCodProvincia())
 && (this.getCodDistrito()==castOther.getCodDistrito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodDepartamento();
         result = 37 * result + this.getCodProvincia();
         result = 37 * result + this.getCodDistrito();
         return result;
   }   


}


