package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AimarNivel3 generated by hbm2java
 */
public class AimarNivel3  implements java.io.Serializable {


     private AimarNivel3Id id;
     private AimarNivel2 aimarNivel2;
     private String desNiv3;
     private String abrNiv3;
     private String flgRegistroaplicacion;
     private String flgRegistroFertilizante;
     private String flgDefecto;
     private String fecCreacion;
     private String horCreacion;
     private Integer codUsuarioCreacion;
     private String fecActualizacion;
     private String horActualizacion;
     private Integer codUsuarioActualizacion;
     private Set<AimarNivel4> aimarNivel4s = new HashSet<AimarNivel4>(0);

    public AimarNivel3() {
    }

	
    public AimarNivel3(AimarNivel3Id id, AimarNivel2 aimarNivel2) {
        this.id = id;
        this.aimarNivel2 = aimarNivel2;
    }
    public AimarNivel3(AimarNivel3Id id, AimarNivel2 aimarNivel2, String desNiv3, String abrNiv3, String flgRegistroaplicacion, String flgRegistroFertilizante, String flgDefecto, String fecCreacion, String horCreacion, Integer codUsuarioCreacion, String fecActualizacion, String horActualizacion, Integer codUsuarioActualizacion, Set<AimarNivel4> aimarNivel4s) {
       this.id = id;
       this.aimarNivel2 = aimarNivel2;
       this.desNiv3 = desNiv3;
       this.abrNiv3 = abrNiv3;
       this.flgRegistroaplicacion = flgRegistroaplicacion;
       this.flgRegistroFertilizante = flgRegistroFertilizante;
       this.flgDefecto = flgDefecto;
       this.fecCreacion = fecCreacion;
       this.horCreacion = horCreacion;
       this.codUsuarioCreacion = codUsuarioCreacion;
       this.fecActualizacion = fecActualizacion;
       this.horActualizacion = horActualizacion;
       this.codUsuarioActualizacion = codUsuarioActualizacion;
       this.aimarNivel4s = aimarNivel4s;
    }
   
    public AimarNivel3Id getId() {
        return this.id;
    }
    
    public void setId(AimarNivel3Id id) {
        this.id = id;
    }
    public AimarNivel2 getAimarNivel2() {
        return this.aimarNivel2;
    }
    
    public void setAimarNivel2(AimarNivel2 aimarNivel2) {
        this.aimarNivel2 = aimarNivel2;
    }
    public String getDesNiv3() {
        return this.desNiv3;
    }
    
    public void setDesNiv3(String desNiv3) {
        this.desNiv3 = desNiv3;
    }
    public String getAbrNiv3() {
        return this.abrNiv3;
    }
    
    public void setAbrNiv3(String abrNiv3) {
        this.abrNiv3 = abrNiv3;
    }
    public String getFlgRegistroaplicacion() {
        return this.flgRegistroaplicacion;
    }
    
    public void setFlgRegistroaplicacion(String flgRegistroaplicacion) {
        this.flgRegistroaplicacion = flgRegistroaplicacion;
    }
    public String getFlgRegistroFertilizante() {
        return this.flgRegistroFertilizante;
    }
    
    public void setFlgRegistroFertilizante(String flgRegistroFertilizante) {
        this.flgRegistroFertilizante = flgRegistroFertilizante;
    }
    public String getFlgDefecto() {
        return this.flgDefecto;
    }
    
    public void setFlgDefecto(String flgDefecto) {
        this.flgDefecto = flgDefecto;
    }
    public String getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getHorCreacion() {
        return this.horCreacion;
    }
    
    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }
    public Integer getCodUsuarioCreacion() {
        return this.codUsuarioCreacion;
    }
    
    public void setCodUsuarioCreacion(Integer codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }
    public String getFecActualizacion() {
        return this.fecActualizacion;
    }
    
    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }
    public String getHorActualizacion() {
        return this.horActualizacion;
    }
    
    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }
    public Integer getCodUsuarioActualizacion() {
        return this.codUsuarioActualizacion;
    }
    
    public void setCodUsuarioActualizacion(Integer codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }
    public Set<AimarNivel4> getAimarNivel4s() {
        return this.aimarNivel4s;
    }
    
    public void setAimarNivel4s(Set<AimarNivel4> aimarNivel4s) {
        this.aimarNivel4s = aimarNivel4s;
    }




}


