package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AimarNivel2 generated by hbm2java
 */
public class AimarNivel2  implements java.io.Serializable {


     private AimarNivel2Id id;
     private AimarNivel1 aimarNivel1;
     private String desNiv2;
     private String abrNiv2;
     private String flgRegistroaplicacion;
     private String flgRegistroFertilizante;
     private String flgDefecto;
     private String fecCreacion;
     private String horCreacion;
     private Integer codUsuarioCreacion;
     private String fecActualizacion;
     private String horActualizacion;
     private Integer codUsuarioActualizacion;
     private Set<AimarNivel3> aimarNivel3s = new HashSet<AimarNivel3>(0);

    public AimarNivel2() {
    }

	
    public AimarNivel2(AimarNivel2Id id, AimarNivel1 aimarNivel1) {
        this.id = id;
        this.aimarNivel1 = aimarNivel1;
    }
    public AimarNivel2(AimarNivel2Id id, AimarNivel1 aimarNivel1, String desNiv2, String abrNiv2, String flgRegistroaplicacion, String flgRegistroFertilizante, String flgDefecto, String fecCreacion, String horCreacion, Integer codUsuarioCreacion, String fecActualizacion, String horActualizacion, Integer codUsuarioActualizacion, Set<AimarNivel3> aimarNivel3s) {
       this.id = id;
       this.aimarNivel1 = aimarNivel1;
       this.desNiv2 = desNiv2;
       this.abrNiv2 = abrNiv2;
       this.flgRegistroaplicacion = flgRegistroaplicacion;
       this.flgRegistroFertilizante = flgRegistroFertilizante;
       this.flgDefecto = flgDefecto;
       this.fecCreacion = fecCreacion;
       this.horCreacion = horCreacion;
       this.codUsuarioCreacion = codUsuarioCreacion;
       this.fecActualizacion = fecActualizacion;
       this.horActualizacion = horActualizacion;
       this.codUsuarioActualizacion = codUsuarioActualizacion;
       this.aimarNivel3s = aimarNivel3s;
    }
   
    public AimarNivel2Id getId() {
        return this.id;
    }
    
    public void setId(AimarNivel2Id id) {
        this.id = id;
    }
    public AimarNivel1 getAimarNivel1() {
        return this.aimarNivel1;
    }
    
    public void setAimarNivel1(AimarNivel1 aimarNivel1) {
        this.aimarNivel1 = aimarNivel1;
    }
    public String getDesNiv2() {
        return this.desNiv2;
    }
    
    public void setDesNiv2(String desNiv2) {
        this.desNiv2 = desNiv2;
    }
    public String getAbrNiv2() {
        return this.abrNiv2;
    }
    
    public void setAbrNiv2(String abrNiv2) {
        this.abrNiv2 = abrNiv2;
    }
    public String getFlgRegistroaplicacion() {
        return this.flgRegistroaplicacion;
    }
    
    public void setFlgRegistroaplicacion(String flgRegistroaplicacion) {
        this.flgRegistroaplicacion = flgRegistroaplicacion;
    }
    public String getFlgRegistroFertilizante() {
        return this.flgRegistroFertilizante;
    }
    
    public void setFlgRegistroFertilizante(String flgRegistroFertilizante) {
        this.flgRegistroFertilizante = flgRegistroFertilizante;
    }
    public String getFlgDefecto() {
        return this.flgDefecto;
    }
    
    public void setFlgDefecto(String flgDefecto) {
        this.flgDefecto = flgDefecto;
    }
    public String getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getHorCreacion() {
        return this.horCreacion;
    }
    
    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }
    public Integer getCodUsuarioCreacion() {
        return this.codUsuarioCreacion;
    }
    
    public void setCodUsuarioCreacion(Integer codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }
    public String getFecActualizacion() {
        return this.fecActualizacion;
    }
    
    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }
    public String getHorActualizacion() {
        return this.horActualizacion;
    }
    
    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }
    public Integer getCodUsuarioActualizacion() {
        return this.codUsuarioActualizacion;
    }
    
    public void setCodUsuarioActualizacion(Integer codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }
    public Set<AimarNivel3> getAimarNivel3s() {
        return this.aimarNivel3s;
    }
    
    public void setAimarNivel3s(Set<AimarNivel3> aimarNivel3s) {
        this.aimarNivel3s = aimarNivel3s;
    }




}


