package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AimarNivel4 generated by hbm2java
 */
public class AimarNivel4  implements java.io.Serializable {


     private AimarNivel4Id id;
     private AimarNivel3 aimarNivel3;
     private String desNiv4;
     private String abrNiv4;
     private String flgRegistroaplicacion;
     private String flgRegistroFertilizante;
     private String flgDefecto;
     private String fecCreacion;
     private String horCreacion;
     private Integer codUsuarioCreacion;
     private String fecActualizacion;
     private String horActualizacion;
     private Integer codUsuarioActualizacion;
     private Set<AimarNivel5> aimarNivel5s = new HashSet<AimarNivel5>(0);

    public AimarNivel4() {
    }

	
    public AimarNivel4(AimarNivel4Id id, AimarNivel3 aimarNivel3) {
        this.id = id;
        this.aimarNivel3 = aimarNivel3;
    }
    public AimarNivel4(AimarNivel4Id id, AimarNivel3 aimarNivel3, String desNiv4, String abrNiv4, String flgRegistroaplicacion, String flgRegistroFertilizante, String flgDefecto, String fecCreacion, String horCreacion, Integer codUsuarioCreacion, String fecActualizacion, String horActualizacion, Integer codUsuarioActualizacion, Set<AimarNivel5> aimarNivel5s) {
       this.id = id;
       this.aimarNivel3 = aimarNivel3;
       this.desNiv4 = desNiv4;
       this.abrNiv4 = abrNiv4;
       this.flgRegistroaplicacion = flgRegistroaplicacion;
       this.flgRegistroFertilizante = flgRegistroFertilizante;
       this.flgDefecto = flgDefecto;
       this.fecCreacion = fecCreacion;
       this.horCreacion = horCreacion;
       this.codUsuarioCreacion = codUsuarioCreacion;
       this.fecActualizacion = fecActualizacion;
       this.horActualizacion = horActualizacion;
       this.codUsuarioActualizacion = codUsuarioActualizacion;
       this.aimarNivel5s = aimarNivel5s;
    }
   
    public AimarNivel4Id getId() {
        return this.id;
    }
    
    public void setId(AimarNivel4Id id) {
        this.id = id;
    }
    public AimarNivel3 getAimarNivel3() {
        return this.aimarNivel3;
    }
    
    public void setAimarNivel3(AimarNivel3 aimarNivel3) {
        this.aimarNivel3 = aimarNivel3;
    }
    public String getDesNiv4() {
        return this.desNiv4;
    }
    
    public void setDesNiv4(String desNiv4) {
        this.desNiv4 = desNiv4;
    }
    public String getAbrNiv4() {
        return this.abrNiv4;
    }
    
    public void setAbrNiv4(String abrNiv4) {
        this.abrNiv4 = abrNiv4;
    }
    public String getFlgRegistroaplicacion() {
        return this.flgRegistroaplicacion;
    }
    
    public void setFlgRegistroaplicacion(String flgRegistroaplicacion) {
        this.flgRegistroaplicacion = flgRegistroaplicacion;
    }
    public String getFlgRegistroFertilizante() {
        return this.flgRegistroFertilizante;
    }
    
    public void setFlgRegistroFertilizante(String flgRegistroFertilizante) {
        this.flgRegistroFertilizante = flgRegistroFertilizante;
    }
    public String getFlgDefecto() {
        return this.flgDefecto;
    }
    
    public void setFlgDefecto(String flgDefecto) {
        this.flgDefecto = flgDefecto;
    }
    public String getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getHorCreacion() {
        return this.horCreacion;
    }
    
    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }
    public Integer getCodUsuarioCreacion() {
        return this.codUsuarioCreacion;
    }
    
    public void setCodUsuarioCreacion(Integer codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }
    public String getFecActualizacion() {
        return this.fecActualizacion;
    }
    
    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }
    public String getHorActualizacion() {
        return this.horActualizacion;
    }
    
    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }
    public Integer getCodUsuarioActualizacion() {
        return this.codUsuarioActualizacion;
    }
    
    public void setCodUsuarioActualizacion(Integer codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }
    public Set<AimarNivel5> getAimarNivel5s() {
        return this.aimarNivel5s;
    }
    
    public void setAimarNivel5s(Set<AimarNivel5> aimarNivel5s) {
        this.aimarNivel5s = aimarNivel5s;
    }




}


