package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AimarNivel1 generated by hbm2java
 */
public class AimarNivel1  implements java.io.Serializable {


     private AimarNivel1Id id;
     private String desNiv1;
     private String abrNiv1;
     private String flgServicio;
     private String flgRegistroaplicacion;
     private String flgRegistroFertilizante;
     private String flgDefecto;
     private String fecCreacion;
     private String horCreacion;
     private Integer codUsuarioCreacion;
     private String fecActualizacion;
     private String horActualizacion;
     private Integer codUsuarioActualizacion;
     private Set<AimarNivel2> aimarNivel2s = new HashSet<AimarNivel2>(0);

    public AimarNivel1() {
    }

	
    public AimarNivel1(AimarNivel1Id id) {
        this.id = id;
    }
    public AimarNivel1(AimarNivel1Id id, String desNiv1, String abrNiv1, String flgServicio, String flgRegistroaplicacion, String flgRegistroFertilizante, String flgDefecto, String fecCreacion, String horCreacion, Integer codUsuarioCreacion, String fecActualizacion, String horActualizacion, Integer codUsuarioActualizacion, Set<AimarNivel2> aimarNivel2s) {
       this.id = id;
       this.desNiv1 = desNiv1;
       this.abrNiv1 = abrNiv1;
       this.flgServicio = flgServicio;
       this.flgRegistroaplicacion = flgRegistroaplicacion;
       this.flgRegistroFertilizante = flgRegistroFertilizante;
       this.flgDefecto = flgDefecto;
       this.fecCreacion = fecCreacion;
       this.horCreacion = horCreacion;
       this.codUsuarioCreacion = codUsuarioCreacion;
       this.fecActualizacion = fecActualizacion;
       this.horActualizacion = horActualizacion;
       this.codUsuarioActualizacion = codUsuarioActualizacion;
       this.aimarNivel2s = aimarNivel2s;
    }
   
    public AimarNivel1Id getId() {
        return this.id;
    }
    
    public void setId(AimarNivel1Id id) {
        this.id = id;
    }
    public String getDesNiv1() {
        return this.desNiv1;
    }
    
    public void setDesNiv1(String desNiv1) {
        this.desNiv1 = desNiv1;
    }
    public String getAbrNiv1() {
        return this.abrNiv1;
    }
    
    public void setAbrNiv1(String abrNiv1) {
        this.abrNiv1 = abrNiv1;
    }
    public String getFlgServicio() {
        return this.flgServicio;
    }
    
    public void setFlgServicio(String flgServicio) {
        this.flgServicio = flgServicio;
    }
    public String getFlgRegistroaplicacion() {
        return this.flgRegistroaplicacion;
    }
    
    public void setFlgRegistroaplicacion(String flgRegistroaplicacion) {
        this.flgRegistroaplicacion = flgRegistroaplicacion;
    }
    public String getFlgRegistroFertilizante() {
        return this.flgRegistroFertilizante;
    }
    
    public void setFlgRegistroFertilizante(String flgRegistroFertilizante) {
        this.flgRegistroFertilizante = flgRegistroFertilizante;
    }
    public String getFlgDefecto() {
        return this.flgDefecto;
    }
    
    public void setFlgDefecto(String flgDefecto) {
        this.flgDefecto = flgDefecto;
    }
    public String getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getHorCreacion() {
        return this.horCreacion;
    }
    
    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }
    public Integer getCodUsuarioCreacion() {
        return this.codUsuarioCreacion;
    }
    
    public void setCodUsuarioCreacion(Integer codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }
    public String getFecActualizacion() {
        return this.fecActualizacion;
    }
    
    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }
    public String getHorActualizacion() {
        return this.horActualizacion;
    }
    
    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }
    public Integer getCodUsuarioActualizacion() {
        return this.codUsuarioActualizacion;
    }
    
    public void setCodUsuarioActualizacion(Integer codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }
    public Set<AimarNivel2> getAimarNivel2s() {
        return this.aimarNivel2s;
    }
    
    public void setAimarNivel2s(Set<AimarNivel2> aimarNivel2s) {
        this.aimarNivel2s = aimarNivel2s;
    }




}


