package sys.agregar;
// Generated 29-abr-2017 17:18:09 by Hibernate Tools 4.3.1



/**
 * AimarNivel5 generated by hbm2java
 */
public class AimarNivel5  implements java.io.Serializable {


     private AimarNivel5Id id;
     private AimarNivel4 aimarNivel4;
     private String desNiv5;
     private String abrNiv5;
     private String flgRegistroaplicacion;
     private String flgRegistroFertilizante;
     private String flgDefecto;
     private String fecCreacion;
     private String horCreacion;
     private Integer codUsuarioCreacion;
     private String fecActualizacion;
     private String horActualizacion;
     private Integer codUsuarioActualizacion;

    public AimarNivel5() {
    }

	
    public AimarNivel5(AimarNivel5Id id, AimarNivel4 aimarNivel4) {
        this.id = id;
        this.aimarNivel4 = aimarNivel4;
    }
    public AimarNivel5(AimarNivel5Id id, AimarNivel4 aimarNivel4, String desNiv5, String abrNiv5, String flgRegistroaplicacion, String flgRegistroFertilizante, String flgDefecto, String fecCreacion, String horCreacion, Integer codUsuarioCreacion, String fecActualizacion, String horActualizacion, Integer codUsuarioActualizacion) {
       this.id = id;
       this.aimarNivel4 = aimarNivel4;
       this.desNiv5 = desNiv5;
       this.abrNiv5 = abrNiv5;
       this.flgRegistroaplicacion = flgRegistroaplicacion;
       this.flgRegistroFertilizante = flgRegistroFertilizante;
       this.flgDefecto = flgDefecto;
       this.fecCreacion = fecCreacion;
       this.horCreacion = horCreacion;
       this.codUsuarioCreacion = codUsuarioCreacion;
       this.fecActualizacion = fecActualizacion;
       this.horActualizacion = horActualizacion;
       this.codUsuarioActualizacion = codUsuarioActualizacion;
    }
   
    public AimarNivel5Id getId() {
        return this.id;
    }
    
    public void setId(AimarNivel5Id id) {
        this.id = id;
    }
    public AimarNivel4 getAimarNivel4() {
        return this.aimarNivel4;
    }
    
    public void setAimarNivel4(AimarNivel4 aimarNivel4) {
        this.aimarNivel4 = aimarNivel4;
    }
    public String getDesNiv5() {
        return this.desNiv5;
    }
    
    public void setDesNiv5(String desNiv5) {
        this.desNiv5 = desNiv5;
    }
    public String getAbrNiv5() {
        return this.abrNiv5;
    }
    
    public void setAbrNiv5(String abrNiv5) {
        this.abrNiv5 = abrNiv5;
    }
    public String getFlgRegistroaplicacion() {
        return this.flgRegistroaplicacion;
    }
    
    public void setFlgRegistroaplicacion(String flgRegistroaplicacion) {
        this.flgRegistroaplicacion = flgRegistroaplicacion;
    }
    public String getFlgRegistroFertilizante() {
        return this.flgRegistroFertilizante;
    }
    
    public void setFlgRegistroFertilizante(String flgRegistroFertilizante) {
        this.flgRegistroFertilizante = flgRegistroFertilizante;
    }
    public String getFlgDefecto() {
        return this.flgDefecto;
    }
    
    public void setFlgDefecto(String flgDefecto) {
        this.flgDefecto = flgDefecto;
    }
    public String getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getHorCreacion() {
        return this.horCreacion;
    }
    
    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }
    public Integer getCodUsuarioCreacion() {
        return this.codUsuarioCreacion;
    }
    
    public void setCodUsuarioCreacion(Integer codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }
    public String getFecActualizacion() {
        return this.fecActualizacion;
    }
    
    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }
    public String getHorActualizacion() {
        return this.horActualizacion;
    }
    
    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }
    public Integer getCodUsuarioActualizacion() {
        return this.codUsuarioActualizacion;
    }
    
    public void setCodUsuarioActualizacion(Integer codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }




}


