package sys.model;
// Generated 29-abr-2017 17:34:06 by Hibernate Tools 4.3.1

/**
 * AgmaeUsuario generated by hbm2java
 */
public class AgmaeUsuario implements java.io.Serializable {

    private int codUsuario;
    private String nomUsuario;
    private String estActividad;
    private String loginUsuario;
    private String claveUsuario;
    private String correoUsuario;
    private int codPersona;
    private byte[] imagenFirma;
    private String usuarioMail;
    private String passwordMail;
    private String flgOutlook;
    private String desFuncion;
    private String flgAsientoContableInv;
    private String cesUsuario;
    private String fecCreacion;
    private String horCreacion;
    private int codUsuarioCreacion;
    private String fecActualizacion;
    private String horActualizacion;
    private int codUsuarioActualizacion;
    
    private String rucCompanyia;
    private String codEstablecimiento;
    private int codCentroc;
    private int codArea;
    private int codAlmacen;

    private AgmaeEstablecimiento agmaeEstablecimiento;
    private AgmaeCentrocosto agmaeCentrocosto;
    private AgmaeArea agmaeArea;
    private AimarAlmacen aimarAlmacen;

    public AgmaeUsuario() {
        agmaeEstablecimiento = new AgmaeEstablecimiento();
        agmaeCentrocosto = new AgmaeCentrocosto();
        agmaeArea = new AgmaeArea();
        aimarAlmacen = new AimarAlmacen();

    }

    public int getCodUsuario() {
        return codUsuario;
    }

    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }

    public String getNomUsuario() {
        return nomUsuario;
    }

    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }

    public String getEstActividad() {
        return estActividad;
    }

    public void setEstActividad(String estActividad) {
        this.estActividad = estActividad;
    }

    public String getLoginUsuario() {
        return loginUsuario;
    }

    public void setLoginUsuario(String loginUsuario) {
        this.loginUsuario = loginUsuario;
    }

    public String getClaveUsuario() {
        return claveUsuario;
    }

    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }

    public String getCorreoUsuario() {
        return correoUsuario;
    }

    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }

    public int getCodPersona() {
        return codPersona;
    }

    public void setCodPersona(int codPersona) {
        this.codPersona = codPersona;
    }

    public byte[] getImagenFirma() {
        return imagenFirma;
    }

    public void setImagenFirma(byte[] imagenFirma) {
        this.imagenFirma = imagenFirma;
    }

    public String getUsuarioMail() {
        return usuarioMail;
    }

    public void setUsuarioMail(String usuarioMail) {
        this.usuarioMail = usuarioMail;
    }

    public String getPasswordMail() {
        return passwordMail;
    }

    public void setPasswordMail(String passwordMail) {
        this.passwordMail = passwordMail;
    }

    public String getFlgOutlook() {
        return flgOutlook;
    }

    public void setFlgOutlook(String flgOutlook) {
        this.flgOutlook = flgOutlook;
    }

    public String getDesFuncion() {
        return desFuncion;
    }

    public void setDesFuncion(String desFuncion) {
        this.desFuncion = desFuncion;
    }

    public String getFlgAsientoContableInv() {
        return flgAsientoContableInv;
    }

    public void setFlgAsientoContableInv(String flgAsientoContableInv) {
        this.flgAsientoContableInv = flgAsientoContableInv;
    }

    public String getCesUsuario() {
        return cesUsuario;
    }

    public void setCesUsuario(String cesUsuario) {
        this.cesUsuario = cesUsuario;
    }

    public String getFecCreacion() {
        return fecCreacion;
    }

    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }

    public String getHorCreacion() {
        return horCreacion;
    }

    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }

    public int getCodUsuarioCreacion() {
        return codUsuarioCreacion;
    }

    public void setCodUsuarioCreacion(int codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }

    public String getFecActualizacion() {
        return fecActualizacion;
    }

    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }

    public String getHorActualizacion() {
        return horActualizacion;
    }

    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }

    public int getCodUsuarioActualizacion() {
        return codUsuarioActualizacion;
    }

    public void setCodUsuarioActualizacion(int codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }

    public String getRucCompanyia() {
        return rucCompanyia;
    }

    public void setRucCompanyia(String rucCompanyia) {
        this.rucCompanyia = rucCompanyia;
    }

    public String getCodEstablecimiento() {
        return codEstablecimiento;
    }

    public void setCodEstablecimiento(String codEstablecimiento) {
        this.codEstablecimiento = codEstablecimiento;
    }

    public int getCodCentroc() {
        return codCentroc;
    }

    public void setCodCentroc(int codCentroc) {
        this.codCentroc = codCentroc;
    }

    public int getCodArea() {
        return codArea;
    }

    public void setCodArea(int codArea) {
        this.codArea = codArea;
    }

    public int getCodAlmacen() {
        return codAlmacen;
    }

    public void setCodAlmacen(int codAlmacen) {
        this.codAlmacen = codAlmacen;
    }
    
    

    public AgmaeEstablecimiento getAgmaeEstablecimiento() {
        return agmaeEstablecimiento;
    }

    public void setAgmaeEstablecimiento(AgmaeEstablecimiento agmaeEstablecimiento) {
        this.agmaeEstablecimiento = agmaeEstablecimiento;
    }

    public AgmaeCentrocosto getAgmaeCentrocosto() {
        return agmaeCentrocosto;
    }

    public void setAgmaeCentrocosto(AgmaeCentrocosto agmaeCentrocosto) {
        this.agmaeCentrocosto = agmaeCentrocosto;
    }

    public AgmaeArea getAgmaeArea() {
        return agmaeArea;
    }

    public void setAgmaeArea(AgmaeArea agmaeArea) {
        this.agmaeArea = agmaeArea;
    }

    public AimarAlmacen getAimarAlmacen() {
        return aimarAlmacen;
    }

    public void setAimarAlmacen(AimarAlmacen aimarAlmacen) {
        this.aimarAlmacen = aimarAlmacen;
    }

}
