package sys.model;
// Generated 29-abr-2017 17:34:06 by Hibernate Tools 4.3.1

/**
 * AgmaeUsuarioAccesos generated by hbm2java
 */
public class AgmaeUsuarioAccesos implements java.io.Serializable {

    private int codUsuario;
    private String rucCompanyia;
    private String codSistema;
    private String codModulo;
    private String codOpcion;
    private String desModulo;
    private String nomUsuario;
    private String codNuevo;
    private String codEditar;
    private String codEliminar;
    private String cesUsuarioAccesos;
    private String fecCreacion;
    private String horCreacion;
    private int codUsuarioCreacion;
    private String fecActualizacion;
    private String horActualizacion;
    private int codUsuarioActualizacion;

    public AgmaeUsuarioAccesos() {
    }

    public int getCodUsuario() {
        return codUsuario;
    }

    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }

    public String getRucCompanyia() {
        return rucCompanyia;
    }

    public void setRucCompanyia(String rucCompanyia) {
        this.rucCompanyia = rucCompanyia;
    }

    public String getCodSistema() {
        return codSistema;
    }

    public void setCodSistema(String codSistema) {
        this.codSistema = codSistema;
    }

    public String getCodModulo() {
        return codModulo;
    }

    public void setCodModulo(String codModulo) {
        this.codModulo = codModulo;
    }

    public String getCodOpcion() {
        return codOpcion;
    }

    public void setCodOpcion(String codOpcion) {
        this.codOpcion = codOpcion;
    }

    public String getDesModulo() {
        return desModulo;
    }

    public void setDesModulo(String desModulo) {
        this.desModulo = desModulo;
    }

    public String getNomUsuario() {
        return this.nomUsuario;
    }

    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }

    public String getCodNuevo() {
        return this.codNuevo;
    }

    public void setCodNuevo(String codNuevo) {
        this.codNuevo = codNuevo;
    }

    public String getCodEditar() {
        return this.codEditar;
    }

    public void setCodEditar(String codEditar) {
        this.codEditar = codEditar;
    }

    public String getCodEliminar() {
        return this.codEliminar;
    }

    public void setCodEliminar(String codEliminar) {
        this.codEliminar = codEliminar;
    }

    public String getCesUsuarioAccesos() {
        return this.cesUsuarioAccesos;
    }

    public void setCesUsuarioAccesos(String cesUsuarioAccesos) {
        this.cesUsuarioAccesos = cesUsuarioAccesos;
    }

    public String getFecCreacion() {
        return this.fecCreacion;
    }

    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }

    public String getHorCreacion() {
        return this.horCreacion;
    }

    public void setHorCreacion(String horCreacion) {
        this.horCreacion = horCreacion;
    }

    public int getCodUsuarioCreacion() {
        return this.codUsuarioCreacion;
    }

    public void setCodUsuarioCreacion(int codUsuarioCreacion) {
        this.codUsuarioCreacion = codUsuarioCreacion;
    }

    public String getFecActualizacion() {
        return this.fecActualizacion;
    }

    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }

    public String getHorActualizacion() {
        return this.horActualizacion;
    }

    public void setHorActualizacion(String horActualizacion) {
        this.horActualizacion = horActualizacion;
    }

    public int getCodUsuarioActualizacion() {
        return this.codUsuarioActualizacion;
    }

    public void setCodUsuarioActualizacion(int codUsuarioActualizacion) {
        this.codUsuarioActualizacion = codUsuarioActualizacion;
    }

}
